-- ElectroHub Database Export
-- Generated on 5/1/2026, 6:42:39 PM

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';

-- Table: users
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (1, 'System Admin', 'admin@electrohub.com', '$2b$10$CzG34ATfaqFA5D43kJsNYey5jUrOcpXh7g.ZfnUAiNkc3lV75ZPE2', 'admin', '2026-04-24T08:44:51.700Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (4, 'Chris P.', 'chrisp@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (5, 'Amanda J.', 'amandaj@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (6, 'Emily R.', 'emilyr@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (7, 'David L.', 'davidl@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (8, 'Jessica W.', 'jessicaw@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (9, 'Michael B.', 'michaelb@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (10, 'Jordan K.', 'jordank@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (11, 'Ryan S.', 'ryans@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (12, 'Alex T.', 'alext@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, created_at, phone, address, reset_token, reset_token_expiry) VALUES (13, 'Sarah M.', 'sarahm@electrohub.local', '$2b$10$udQwkfVFcAqPlTbYyLNmPuEOpJQwSkzrTo2MLHw4SUbXZCpC/mM9S', 'customer', '2026-04-26T03:28:02.234Z', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;

-- Table: categories
INSERT INTO categories (id, name, slug) VALUES (5, 'Computing', 'computing') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (6, 'Acoustics', 'acoustics') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (7, 'Mobile', 'mobile') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (8, 'Wearables', 'wearables') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (9, 'Gaming', 'gaming') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (10, 'Smart Home', 'smart-home') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, slug) VALUES (15, 'Gaming & VR', 'gaming-vr') ON CONFLICT DO NOTHING;

-- Table: products
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (48, 5, 'Dell XPS 15 OLED', 'Next-level performance with a stunning 15.6-inch OLED touchscreen display, Intel Core i7, and NVIDIA RTX 4070 graphics.', '1899.99', 12, 'dell-xps-15.avif', '4.0', false, NULL, '2026-04-25T15:57:14.492Z', '[{"text":"It''s okay, nothing special but it works.","author":"Chris P.","rating":5,"user_id":4},{"text":"Really solid product, works exactly as described.","author":"Amanda J.","rating":3,"user_id":5}]'::jsonb, false, 'Dell') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (47, 5, 'Apple MacBook Air M3 (13-inch)', 'Supercharged by the M3 chip. Features a Liquid Retina display, up to 18 hours of battery life.', '1099.00', 45, 'macbook-air-m3.webp', '3.7', true, NULL, '2026-04-25T15:57:13.507Z', '[{"text":"Five stars! Best purchase I''ve made this year.","author":"Emily R.","rating":3,"user_id":6},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Chris P.","rating":5,"user_id":4},{"text":"Incredible build quality. Feels very premium.","author":"David L.","rating":3,"user_id":7}]'::jsonb, false, 'Apple') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (50, 5, 'Apple iPad Pro 12.9-inch (M2)', 'Astonishing performance. Incredibly advanced displays. Superfast wireless connectivity. Next-level Apple Pencil capabilities.', '1099.00', 60, 'ipad-pro-m2.webp', '3.5', true, NULL, '2026-04-25T15:57:15.064Z', '[{"text":"Really solid product, works exactly as described.","author":"Jessica W.","rating":3,"user_id":8},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Amanda J.","rating":3,"user_id":5},{"text":"Not bad, it does the job.","author":"Emily R.","rating":3,"user_id":6},{"text":"Not bad, it does the job.","author":"Jessica W.","rating":5,"user_id":8}]'::jsonb, false, 'Apple') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (59, 8, 'Apple Watch Series 9', 'Powerful fitness and health tracking with a brilliant always-on display, ECG monitoring, and crash detection.', '399.00', 109, 'apple-watch.webp', '4.0', true, NULL, '2026-04-25T15:57:17.650Z', '[{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Jessica W.","rating":4,"user_id":8}]'::jsonb, false, 'Apple') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (49, 5, 'Asus ROG Zephyrus G14', 'The ultimate compact gaming laptop featuring an AMD Ryzen 9 processor, RTX 4060 GPU, and an incredible ROG Nebula HDR Display.', '1599.00', 20, 'asus-rog-g14.webp', '3.2', false, NULL, '2026-04-25T15:57:14.772Z', '[{"text":"Fantastic value for money. Highly recommended.","author":"Jessica W.","rating":4,"user_id":8},{"text":"Not bad, it does the job.","author":"Chris P.","rating":3,"user_id":4},{"text":"Not bad, it does the job.","author":"Amanda J.","rating":3,"user_id":5},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Michael B.","rating":3,"user_id":9},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Amanda J.","rating":3,"user_id":5}]'::jsonb, false, 'Asus') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (66, 15, 'Nintendo Switch OLED Model', 'Play at home or on the go with a vibrant 7-inch OLED screen, a wide adjustable stand, and enhanced audio.', '349.99', 90, 'switch-oled.webp', '3.3', true, NULL, '2026-04-25T15:57:20.275Z', '[{"text":"Five stars! Best purchase I''ve made this year.","author":"Michael B.","rating":3,"user_id":9},{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"Jessica W.","rating":4,"user_id":8},{"text":"Five stars! Best purchase I''ve made this year.","author":"Jordan K.","rating":3,"user_id":10}]'::jsonb, false, 'Nintendo') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (65, 15, 'Xbox Series X 1TB Console', 'The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power and 4K gaming.', '499.99', 40, 'xbox-series-x.webp', '3.3', false, NULL, '2026-04-25T15:57:19.983Z', '[{"text":"Incredible build quality. Feels very premium.","author":"Ryan S.","rating":4,"user_id":11},{"text":"Incredible build quality. Feels very premium.","author":"Jessica W.","rating":3,"user_id":8},{"text":"Absolutely love it. Great quality and fast shipping!","author":"Emily R.","rating":3,"user_id":6}]'::jsonb, false, 'Microsoft') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (51, 6, 'Sony WH-1000XM5 Wireless Headphones', 'Industry-leading noise cancellation, crystal clear hands-free calling, and up to 30 hours of battery life.', '398.00', 120, 'sony-wh1000xm5.webp', '5.0', true, NULL, '2026-04-25T15:57:15.349Z', '[{"text":"Incredible build quality. Feels very premium.","author":"Alex T.","rating":5,"user_id":12},{"text":"Absolutely love it. Great quality and fast shipping!","author":"Alex T.","rating":5,"user_id":12}]'::jsonb, false, 'Sony') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (53, 6, 'Bose QuietComfort Ultra Earbuds', 'World-class noise cancellation, spatial audio for more immersive listening, and custom-tune technology that adapts sound to your ears.', '299.00', 85, 'bose-qc-ultra.webp', '3.0', false, NULL, '2026-04-25T15:57:15.923Z', '[{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"Sarah M.","rating":3,"user_id":13}]'::jsonb, false, 'Bose') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (55, 7, 'Apple iPhone 15 Pro Max', 'Forged in titanium. Features the breakthrough A17 Pro chip, a customizable Action button, and the pro camera system.', '1199.00', 85, 'iphone-15.webp', '5.0', true, NULL, '2026-04-25T15:57:16.499Z', '[{"text":"Really solid product, works exactly as described.","author":"Amanda J.","rating":5,"user_id":5}]'::jsonb, false, 'Apple') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (57, 7, 'Google Pixel 8 Pro', 'Engineered by Google, featuring the new Tensor G3 chip, advanced AI photography tools, and a polished aluminum frame.', '999.00', 45, 'pixel-8-pro.webp', '4.8', false, NULL, '2026-04-25T15:57:17.076Z', '[{"text":"Decent for the price, but could be better.","author":"Michael B.","rating":5,"user_id":9},{"text":"Absolutely love it. Great quality and fast shipping!","author":"Amanda J.","rating":5,"user_id":5},{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"Michael B.","rating":5,"user_id":9},{"text":"Not bad, it does the job.","author":"Sarah M.","rating":5,"user_id":13},{"text":"Fantastic value for money. Highly recommended.","author":"Alex T.","rating":4,"user_id":12}]'::jsonb, false, 'Google') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (63, 15, 'Sony PlayStation 5 Slim Console', 'Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with haptic feedback.', '499.00', 50, 'ps5.jpg', '3.0', true, NULL, '2026-04-25T15:57:19.402Z', '[{"text":"Five stars! Best purchase I''ve made this year.","author":"Alex T.","rating":3,"user_id":12}]'::jsonb, false, 'Sony') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (64, 15, 'Meta Quest 3 (128GB)', 'Breakthrough mixed reality headset with full-color passthrough and massive resolution leaps over the previous generation.', '499.99', 80, 'meta-quest-3.jpg', '4.0', false, NULL, '2026-04-25T15:57:19.682Z', '[{"text":"Incredible build quality. Feels very premium.","author":"Emily R.","rating":4,"user_id":6},{"text":"Really solid product, works exactly as described.","author":"Jessica W.","rating":4,"user_id":8}]'::jsonb, false, 'Meta') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (68, 10, 'Ring Video Doorbell Pro 2', 'Premium wired video doorbell with 1536p HD Head-to-Toe Video, 3D Motion Detection, and built-in Alexa Greetings.', '249.99', 35, 'ring-doorbell-pro-2.webp', '4.0', false, NULL, '2026-04-25T15:57:20.850Z', '[{"text":"It''s okay, nothing special but it works.","author":"Jessica W.","rating":5,"user_id":8},{"text":"Decent for the price, but could be better.","author":"Jessica W.","rating":4,"user_id":8},{"text":"Five stars! Best purchase I''ve made this year.","author":"Chris P.","rating":3,"user_id":4}]'::jsonb, false, 'Ring') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (52, 6, 'Apple AirPods Pro (2nd Gen)', 'Rich audio experience with Active Noise Cancellation, Adaptive Transparency, and personalized Spatial Audio.', '249.00', 200, 'airpods-pro.webp', '3.8', false, NULL, '2026-04-25T15:57:15.637Z', '[{"text":"Not bad, it does the job.","author":"Chris P.","rating":5,"user_id":4},{"text":"Fantastic value for money. Highly recommended.","author":"Ryan S.","rating":3,"user_id":11},{"text":"Incredible build quality. Feels very premium.","author":"Emily R.","rating":3,"user_id":6},{"text":"It''s okay, nothing special but it works.","author":"Sarah M.","rating":3,"user_id":13},{"text":"Really solid product, works exactly as described.","author":"Amanda J.","rating":4,"user_id":5},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Sarah M.","rating":5,"user_id":13}]'::jsonb, false, 'Apple') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (54, 6, 'Sennheiser Momentum 4 Wireless', 'Signature sound with outstanding music quality, adaptive noise cancellation, and a massive 60-hour battery life.', '349.95', 40, 'sennheiser-momentum-4.webp', '3.8', false, NULL, '2026-04-25T15:57:16.213Z', '[{"text":"It''s okay, nothing special but it works.","author":"Jordan K.","rating":3,"user_id":10},{"text":"Absolutely love it. Great quality and fast shipping!","author":"Jessica W.","rating":5,"user_id":8},{"text":"Really solid product, works exactly as described.","author":"Emily R.","rating":4,"user_id":6},{"text":"Not bad, it does the job.","author":"Sarah M.","rating":3,"user_id":13}]'::jsonb, false, 'Sennheiser') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (56, 7, 'Samsung Galaxy S24 Ultra', 'AI-powered smartphone with a massive 200MP camera, built-in S-Pen, and a super-smooth 6.8" 120Hz display.', '1299.99', 65, 'samsung-s24.webp', '3.8', false, NULL, '2026-04-25T15:57:16.790Z', '[{"text":"Not bad, it does the job.","author":"Jordan K.","rating":4,"user_id":10},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Jessica W.","rating":4,"user_id":8},{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"Amanda J.","rating":4,"user_id":5},{"text":"Incredible build quality. Feels very premium.","author":"Emily R.","rating":3,"user_id":6},{"text":"It''s okay, nothing special but it works.","author":"Amanda J.","rating":3,"user_id":5},{"text":"It''s okay, nothing special but it works.","author":"Jessica W.","rating":5,"user_id":8}]'::jsonb, false, 'Samsung') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (58, 7, 'Samsung Galaxy Z Fold 5', 'Unfold a massive 7.6" main display that transforms your phone into a tablet for ultimate productivity and immersive gaming.', '1799.99', 15, 'galaxy-z-fold-5.webp', '4.2', true, NULL, '2026-04-25T15:57:17.363Z', '[{"text":"Fantastic value for money. Highly recommended.","author":"David L.","rating":4,"user_id":7},{"text":"Really solid product, works exactly as described.","author":"David L.","rating":5,"user_id":7},{"text":"Really solid product, works exactly as described.","author":"Jordan K.","rating":4,"user_id":10},{"text":"It''s okay, nothing special but it works.","author":"Amanda J.","rating":3,"user_id":5},{"text":"Five stars! Best purchase I''ve made this year.","author":"Amanda J.","rating":5,"user_id":5}]'::jsonb, false, 'Samsung') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (60, 8, 'Garmin Fenix 7 Pro Sapphire Solar', 'Ultimate multisport GPS smartwatch with solar charging capabilities and advanced performance metrics.', '899.99', 25, 'garmin-fenix.webp', '3.8', false, NULL, '2026-04-25T15:57:18.272Z', '[{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Amanda J.","rating":3,"user_id":5},{"text":"Incredible build quality. Feels very premium.","author":"David L.","rating":4,"user_id":7},{"text":"Five stars! Best purchase I''ve made this year.","author":"Ryan S.","rating":5,"user_id":11},{"text":"Not bad, it does the job.","author":"Jessica W.","rating":4,"user_id":8},{"text":"Incredible build quality. Feels very premium.","author":"Chris P.","rating":4,"user_id":4},{"text":"It''s okay, nothing special but it works.","author":"Emily R.","rating":3,"user_id":6}]'::jsonb, false, 'Garmin') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (61, 8, 'Samsung Galaxy Watch 6 Classic', 'Timeless design with a rotating bezel. Comprehensive health tracking, advanced sleep coaching, and seamless Galaxy ecosystem integration.', '399.99', 55, 'galaxy-watch-6.webp', '3.5', false, NULL, '2026-04-25T15:57:18.729Z', '[{"text":"Really solid product, works exactly as described.","author":"David L.","rating":4,"user_id":7},{"text":"It''s okay, nothing special but it works.","author":"Jessica W.","rating":3,"user_id":8}]'::jsonb, false, 'Samsung') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (62, 8, 'Oura Ring Gen3 Horizon', 'Sleek, titanium smart ring that provides highly accurate, personalized health data including sleep analysis, heart rate, and readiness scores.', '349.00', 30, 'oura-ring-3.webp', '4.2', false, NULL, '2026-04-25T15:57:19.095Z', '[{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"Amanda J.","rating":4,"user_id":5},{"text":"It''s okay, nothing special but it works.","author":"Jessica W.","rating":5,"user_id":8},{"text":"Incredible build quality. Feels very premium.","author":"Amanda J.","rating":5,"user_id":5},{"text":"Fantastic value for money. Highly recommended.","author":"David L.","rating":3,"user_id":7},{"text":"Really solid product, works exactly as described.","author":"Emily R.","rating":4,"user_id":6},{"text":"Fantastic value for money. Highly recommended.","author":"Chris P.","rating":4,"user_id":4}]'::jsonb, false, 'Oura') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (69, 10, 'Amazon Echo Studio', 'High-fidelity smart speaker with 3D audio and Alexa. Features 5 speakers that produce powerful bass and crisp highs.', '199.99', 75, 'echo-studio.webp', '4.0', false, NULL, '2026-04-25T15:57:21.153Z', '[{"text":"Fantastic value for money. Highly recommended.","author":"Emily R.","rating":5,"user_id":6},{"text":"Really solid product, works exactly as described.","author":"Michael B.","rating":4,"user_id":9},{"text":"A bit disappointed with the battery life, but otherwise good.","author":"Sarah M.","rating":3,"user_id":13}]'::jsonb, false, 'Amazon') ON CONFLICT DO NOTHING;
INSERT INTO products (id, category_id, name, description, price, stock, image_path, rating, is_featured, specs, created_at, reviews_data, is_new, brand) VALUES (67, 10, 'Philips Hue White & Color Ambiance Starter Kit', 'Transform your home with 16 million colors and shades of white light. Includes Hub and 3 standard A19 bulbs.', '179.99', 59, 'philips-hue.webp', '4.0', true, NULL, '2026-04-25T15:57:20.563Z', '[{"text":"Fantastic value for money. Highly recommended.","author":"Chris P.","rating":5,"user_id":4},{"text":"Decent for the price, but could be better.","author":"Sarah M.","rating":4,"user_id":13},{"text":"Exceeded my expectations. Would definitely recommend to anyone.","author":"David L.","rating":3,"user_id":7},{"text":"Incredible build quality. Feels very premium.","author":"Michael B.","rating":5,"user_id":9},{"text":"Incredible build quality. Feels very premium.","author":"Sarah M.","rating":4,"user_id":13},{"text":"Incredible build quality. Feels very premium.","author":"Emily R.","rating":3,"user_id":6}]'::jsonb, false, 'Philips') ON CONFLICT DO NOTHING;

-- Table: orders
-- (No data found for orders)

-- Table: order_items
-- (No data found for order_items)

-- Table: notifications
-- (No data found for notifications)

-- Table: contact_messages
-- (No data found for contact_messages)

-- Table: newsletter_subscriptions
-- (No data found for newsletter_subscriptions)

-- Table: coupon_codes
INSERT INTO coupon_codes (id, code, discount_amount, is_active, created_at) VALUES (1, 'ELECTROHUB10', '50.00', true, '2026-04-30T17:12:05.255Z') ON CONFLICT DO NOTHING;
INSERT INTO coupon_codes (id, code, discount_amount, is_active, created_at) VALUES (3, 'SAVE15', '75.00', true, '2026-04-30T17:12:05.255Z') ON CONFLICT DO NOTHING;
INSERT INTO coupon_codes (id, code, discount_amount, is_active, created_at) VALUES (2, 'WELCOME20', '100.00', true, '2026-04-30T17:12:05.255Z') ON CONFLICT DO NOTHING;

-- Table: testimonials
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (1, 'Ahmed Al-Rashid', 'Software Engineer', 'AA', 5, 'The MacBook Air M3 is an absolute beast. Silent, fast, and the battery lasts my entire workday. Best laptop I have ever owned.', 'MacBook Air M3', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (2, 'Sarah Mitchell', 'Graphic Designer', 'SM', 5, 'Sony WH-1000XM5 headphones are incredible. I use them during long design sessions and the noise cancellation lets me focus completely.', 'Sony WH-1000XM5', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (3, 'Omar Khalil', 'University Student', 'OK', 5, 'Got the iPhone 15 Pro from ElectroHub and I am blown away by the camera quality. Fast delivery and great packaging too!', 'iPhone 15 Pro', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (4, 'Emily Chen', 'Content Creator', 'EC', 5, 'The AirPods Pro 2 are life-changing for someone who records content daily. The Adaptive ANC is genuinely magical.', 'AirPods Pro 2nd Gen', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (5, 'James Thornton', 'IT Consultant', 'JT', 4, 'Picked up the Dell XPS 15 OLED for work and the display is stunning. The OLED panel makes everything look vibrant. Very happy with my purchase.', 'Dell XPS 15 OLED', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (6, 'Lina Hamdan', 'Fitness Trainer', 'LH', 5, 'My Garmin Fenix 7X has completely transformed how I track my training. The battery lasts nearly two weeks — no charging anxiety!', 'Garmin Fenix 7X', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (7, 'Carlos Rivera', 'Gamer', 'CR', 5, 'The PS5 I got from ElectroHub was in perfect condition and arrived faster than expected. Customer service was excellent too.', 'PlayStation 5', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;
INSERT INTO testimonials (id, name, role, avatar_initials, rating, message, product, created_at) VALUES (8, 'Nour Abdallah', 'Entrepreneur', 'NA', 5, 'Ordered the Samsung S26 Ultra and the camera is on another level. The S Pen is incredibly useful for signing documents on the go.', 'Samsung Galaxy S26 Ultra', '2026-04-24T08:14:57.870Z') ON CONFLICT DO NOTHING;

